const urls = {
  market: [
    {
      website: "https://coinmarketcap.com/new/",
      api: "/coinmarketcap/new",
      id: 1,
      status: 0,
      process: 0,
    },
    {
      website: "https://coinmarketcap.com/gainers-losers/",
      api: "/coinmarketcap/gl",
      id: 2,
      status: 0,
      process: 0,
    },
    {
      website: "https://www.coingecko.com/en/coins/recently_added",
      api: "/coingecko/recently",
      id: 3,
      status: 0,
      process: 0,
    },
    {
      website: "https://coinvote.cc/coins/1&order_by=today",
      api: "/coinvote/coins",
      id: 4,
      status: 0,
      process: 0,
    },
    {
      website: "https://coinalpha.app/",
      api: "/coinalpha",
      id: 5,
      status: 0,
      process: 1,
    },
    {
      website: "https://coinsniper.net/",
      api: "/coinsniper",
      id: 6,
      status: 0,
      process: 1,
    },
    {
      website: "https://coinhunt.cc/",
      api: "/coinhunt",
      id: 7,
      status: 0,
      process: 0,
    },
    {
      website: "https://www.livecoinwatch.com/trending",
      api: "/livecoinwatch/trending",
      id: 8,
      status: 0,
      process: 0,
    },
    {
      website: "https://100xcoinhunt.com/today",
      api: "/l100xcoinhunt/today",
      id: 9,
      status: 0,
      process: 0,
    },
    {
      website: "https://cointoplist.net/",
      api: "/cointoplist",
      id: 10,
      status: 0,
      process: 0,
    },
    {
      website: "https://freshcoins.io/",
      api: "/freshcoins",
      id: 11,
      status: 0,
      process: 0,
      needProxy: true
    },
    {
      website: "https://cryptotokenspace.com/Tokens",
      api: "/cryptotokenspace/tokens",
      id: 12,
      status: 0,
      process: 1,
    },
    {
      website: "https://www.coinseek.xyz/",
      api: "/coinseek",
      id: 13,
      status: 0,
      process: 1,
    },
    {
      website: "https://gemfinder.cc/",
      api: "/gemfinder",
      id: 14,
      status: 0,
      process: 0,
    },
    {
      website: "https://coindiscovery.app/",
      api: "/coindiscovery",
      id: 15,
      status: 0,
      process: 0,
    },
    {
      website: "https://rival.finance/",
      api: "/rival",
      id: 16,
      status: 0,
      process: 0,
    },
  ],
  dex: [
    {
      website: "https://exchange.pancakeswap.finance/#/swap",
      api: "/pancakeswap/swap",
      id: 17,
      status: 0,
      process: 0,
    },
    {
      website: "https://app.uniswap.org/#/swap",
      api: "/uniswap/swap",
      id: 18,
      status: 0,
      process: 1,
    },
    {
      website: "https://ht.mdex.com/#/swap?lang=zh-CN",
      api: "/mdex/swap",
      id: 19,
      status: 0,
      process: 1,
    },
  ],
  browser: [
    {
      website: "https://bscscan.com/",
      api: "/bscscan",
      id: 20,
      status: 0,
      process: 1,
    },
    {
      website: "https://etherscan.io/",
      api: "/etherscan",
      id: 21,
      status: 0,
      process: 1,
    },
    {
      website: "https://etherscan.io/",
      api: "/etherscan",
      id: 22,
      status: 0,
      process: 1,
    },
  ],
};
export default urls;
